# Generated by Django 2.1.5 on 2020-03-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/users/'),
        ),
    ]
