# Generated by Django 2.1.5 on 2020-03-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_confirmation',
            field=models.BooleanField(default=False, unique=True, verbose_name='Email'),
        ),
    ]
