# Generated by Django 2.1.5 on 2020-03-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200330_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_confirmation',
            field=models.BooleanField(default=False, verbose_name='Email'),
        ),
    ]
