# Generated by Django 2.1.5 on 2020-04-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200401_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpicture',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='projects.Project'),
        ),
    ]
