# Generated by Django 2.1.5 on 2020-03-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
