# Generated by Django 2.1.5 on 2020-03-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpicture',
            name='img_url',
            field=models.ImageField(upload_to='static/imgs/'),
        ),
    ]
