# Generated by Django 2.1.5 on 2020-03-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200328_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projectreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectreport',
            name='updated_at',
        ),
    ]
