# Generated by Django 2.1.5 on 2020-03-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_user'),
        ('projects', '0007_auto_20200328_0012'),
    ]

    operations = [
    ]
