# Generated by Django 2.1.5 on 2020-03-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_merge_20200328_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpicture',
            name='img_url',
            field=models.ImageField(upload_to='static/imgs/'),
        ),
    ]
