# Generated by Django 2.1.5 on 2020-03-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200324_0431'),
        ('projects', '0009_merge_20200328_0016'),
    ]

    operations = [
    ]
