# Generated by Django 2.1.5 on 2020-03-31 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200330_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='insert_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
