# Generated by Django 2.1.5 on 2020-04-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_insert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_icon',
            field=models.ImageField(default=True, upload_to='static/imgs/'),
        ),
    ]
